# Generated by Django 4.2.5 on 2023-09-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner', models.ImageField(upload_to='ban_imgs/')),
                ('Perfil', models.ImageField(upload_to='perf_imgs/')),
                ('NomeLoja', models.CharField(max_length=30)),
                ('NomeVendedor', models.CharField(max_length=50)),
                ('Cpf', models.TextField(max_length=14)),
                ('DataNascimento', models.DateTimeField()),
                ('Localizacao', models.TextField(max_length=50)),
            ],
        ),
    ]
