# Generated by Django 4.2.5 on 2023-09-24 21:12

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Banner", models.ImageField(upload_to="ban_imgs/")),
                ("Perfil", models.ImageField(upload_to="perf_imgs/")),
                ("NomeLoja", models.CharField(max_length=30)),
                ("NomeVendedor", models.CharField(max_length=50)),
                ("Cpf", cpf_field.models.CPFField(max_length=14, verbose_name="cpf")),
                ("DataNascimento", models.DateTimeField()),
            ],
        ),
    ]
