# Generated by Django 4.2.5 on 2023-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
