# Generated by Django 4.1 on 2023-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Kolekto", "0003_produto_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loja",
            name="Cpf",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="loja",
            name="Localizacao",
            field=models.CharField(max_length=50),
        ),
    ]
