# Generated by Django 4.2.5 on 2023-09-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Kolekto", "0004_alter_loja_cpf_alter_loja_localizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="loja",
            name="dados_contato",
            field=models.TextField(default="Sem dados de contato", max_length=200),
        ),
    ]
