# Generated by Django 4.2.5 on 2023-09-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0005_loja_dados_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='loja_id',
            field=models.IntegerField(default=None),
        ),
    ]
