# Generated by Django 4.2.5 on 2023-09-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0006_usuario_produto_loja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='loja_id',
            field=models.IntegerField(null=None),
        ),
    ]
