# Generated by Django 4.2.5 on 2023-09-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0008_alter_produto_loja_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='loja_id',
        ),
    ]
