# Generated by Django 4.2.5 on 2023-09-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0010_rename_dados_contato_loja_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='login',
            new_name='username',
        ),
    ]
