# Generated by Django 4.2.5 on 2023-09-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Kolekto", "0011_rename_login_usuario_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="loja",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Kolekto.loja",
            ),
        ),
    ]
