# Generated by Django 4.2.5 on 2023-09-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Kolekto", "0012_produto_loja"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loja",
            name="NomeVendedor",
        ),
        migrations.AddField(
            model_name="loja",
            name="associado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Kolekto.usuario",
            ),
        ),
    ]
