# Generated by Django 4.2.5 on 2023-09-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0013_remove_loja_nomevendedor_loja_associado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto3',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto4',
        ),
    ]
