# Generated by Django 4.2.5 on 2023-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0015_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[(None, 'Selecione a categoria'), ('Móveis e Decoração', 'Móveis e Decoração'), ('Arte', 'Arte'), ('Joalheria', 'Joalheria'), ('Livros', 'Livros'), ('Relógios', 'Relógios'), ('Cartas', 'Cartas'), ('Brinquedos e Jogos', 'Brinquedos e Jogos'), ('Vestuário', 'Vestuário'), ('Fotografia', 'Fotografia'), ('Instrumento Musical', 'Instrumento Musical'), ('Outro', 'Outro')], default=(None, 'Selecione a categoria'), max_length=50),
        ),
    ]
