# Generated by Django 4.2.5 on 2023-10-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0017_remove_usuario_nome_remove_usuario_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='nome',
        ),
    ]
