# Generated by Django 4.2.5 on 2023-10-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0019_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
