# Generated by Django 4.2.5 on 2023-10-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0020_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='associado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Kolekto.usuario'),
            preserve_default=False,
        ),
    ]
