# Generated by Django 4.2.5 on 2023-10-05 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kolekto', '0021_alter_loja_associado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='associado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
