# Generated by Django 4.2.5 on 2023-10-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0022_alter_loja_associado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto1',
            field=models.CharField(max_length=100),
        ),
    ]
