# Generated by Django 4.2.5 on 2023-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kolekto', '0026_alter_loja_banner_alter_loja_perfil_carrinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
