# Generated by Django 4.2.5 on 2023-11-03 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Kolekto", "0031_compra_destinatario_alter_compra_trasportadora"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loja",
            name="Banner",
        ),
    ]
