# Generated by Django 4.2.5 on 2023-11-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Kolekto", "0032_remove_loja_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="nome_comprador",
            field=models.CharField(default="Não Informado", max_length=50),
        ),
    ]
